### ISSUE TITLE
Do you accept podcast on other languages?

### ISSUE THREAD

**Issue by midudev** [iRaul/podcasts-repo#31]
Hi there! I have a podcast about frontend called WhatTheFront! The podcast is recorded on spanish and I would like to know if I could do a PR adding it to the repo. :) Thanks!

**Comment by iRaul** [comment]
Hey!

Good question.

A solution to this will be to add categories based on other languages?
Let me think about it and come back with an answer soon.

Thank you!

**Comment by midudev** [comment]
Awesome, thanks for your reply! ;)
