### ISSUE TITLE
Redesign the page

### ISSUE THREAD

**Issue by iRaul** [iRaul/podcasts-repo#41]

**Comment by frederic-klein** [comment]
@iRaul Any open tasks I could help with?

**Comment by iRaul** [comment]
@frederic-klein Yes, that'd be awesome.

1. In some cases the title is too long and breaks up in two rows. I want the title to be on a single row.
2. In some cases the description is too long 😬I would like the description to have the podcast's image height. Or just keep the description short.

Let me know if you have any suggestions?

Thanks!

**Comment by frederic-klein** [comment]
@iRaul We could truncate the Text, marking with dots (e.g. _Title title too long from here_ becomes _Title title..._).
If title and/or description is truncated something like a "detail view" should provide the untruncated details: a larger, centered overlay card could solve this.
The dots could be a link or an icon opening the detail view, so the rest of the card still links to the podcast. Alternatively something like an expand icon after the description?

If you don' want to truncate but provide and request sensible titles and descriptions within the limits, we could probably define a rule for eslint and run the lint check on PRs?
